/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

// package com.team3602.teamlibrary

// import kotlin.test.Test
// import kotlin.test.assertTrue

// class LibraryTest {
//     @Test fun someLibraryMethodReturnsTrue() {
//         val classUnderTest = Library()
//         assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
//     }
// }
